-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.24.0
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@^7.24.0
        -   eslint-plugin-react@^7.23.2
