version: "3.8"
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
        env_file:
            - ./dev.env

    queue:
        image: rabbitmq
        volumes:
            - ./queue:/queue

    django:
        build:
            context: backend/
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
            - static:/static
        env_file:
            - ./dev.env
        depends_on:
            - db

    celery:
        restart: always
        build: ./backend
        command: celery -A backend worker -l info
        volumes:
            - ./backend:/app
        env_file:
            - ./dev.env
        depends_on:
            - queue
            - django

    react:
        build:
            context: frontend/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - static:/app/src/admin
        depends_on:
            - django

volumes:
    static:
