version: "3.8"
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    django:
        build:
            context: backend/
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
            - static:/static
        environment:
            - POSTGRES_HOST=db
        depends_on:
            - db

    react:
        build:
            context: frontend/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - static:/app/src/admin
        depends_on:
            - django

volumes:
    static:
