# Generated by Django 3.2 on 2021-04-28 06:43
import classifier.models
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Prediction',
            },
        ),
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'Predictor',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('truncated_uuid', models.CharField(db_index=True, max_length=8)),
                ('search_term', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number_of_tweets', models.PositiveIntegerField()),
                ('empty', models.BooleanField(blank=True, default=False)),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.predictor')),
            ],
            options={
                'db_table': 'Search',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('predictors', models.ManyToManyField(through='classifier.Prediction', to='classifier.Predictor')),
            ],
            options={
                'db_table': 'Tweet',
            },
        ),
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.search')),
            ],
            options={
                'db_table': 'Searcher',
            },
        ),
        migrations.AddField(
            model_name='search',
            name='tweets',
            field=models.ManyToManyField(to='classifier.Tweet'),
        ),
        migrations.CreateModel(
            name='PredictionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('label', models.CharField(max_length=20)),
                ('integer_label', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.predictor')),
            ],
            options={
                'db_table': 'PredictionLabel',
            },
        ),
        migrations.AddField(
            model_name='prediction',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.predictionlabel'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='predictor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.predictor'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.tweet'),
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=classifier.models.logo_filename)),
                ('about', models.TextField()),
                ('enable_email_notification', models.BooleanField(blank=True, default=False)),
                ('allow_user_to_choose_predictor', models.BooleanField(blank=True, default=False)),
                ('allow_user_to_choose_number_of_tweets', models.BooleanField(blank=True, default=False)),
                ('default_predictor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.predictor')),
            ],
            options={
                'db_table': 'App',
            },
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('predictor', 'tweet')},
        ),
    ]
